# i3status configuration file.
# see "man i3status" for documentation.
#
# It is important that this file is edited as UTF-8.
# For FontAwesome icons see: http://fontawesome.io/cheatsheet/
#
# Profile: laptop
################################################################################

general {
	# output_format = "i3bar"
	colors = true
	interval = 1
	color_good = "#2AA198"
	# color_good = "#36E592"
	color_bad = "#FFD300"
	color_degraded = "#DC322F"
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "load"
order += "disk /"
order += "wireless _first_"
# order += "ethernet _first_"
order += "battery 1"
order += "volume master"
order += "tztime local"

cpu_usage {
	# ⚛ ⚙
	format = " %usage"
}

cpu_temperature 0 {
	format = "%degrees°C"
	max_threshold = "65"
}

load {
	format = "⚙ %1min"
	max_threshold = 5
}

disk "/" {
	format = " %avail"
	# format = "⛁ %avail"
}

wireless _first_ {
	format_up = " %essid  %quality  %bitrate  %ip"
	format_down = "no wlan"
}

ethernet _first_ {
	# if you use %speed, i3status requires root privileges
	format_up = " %speed  %ip"
	format_down = "no lan"
}

battery 1 {
	# format = "%status %percentage %remaining %emptytime"
	format = "%status %percentage"
	format_down = "No battery"
	last_full_capacity = true
	integer_battery_capacity = true
	# status_chr = ""
	status_chr = "⚡"
	status_bat = ""
	# status_bat = "bat"
	status_bat = "☉"
	# status_full = ""
	status_full = "☻"
	low_threshold = 15
	threshold_type = time
	path = "/sys/class/power_supply/BAT0/uevent"
}

volume master {
	# TODO: fix volume values
	# https://bbs.archlinux.org/viewtopic.php?id=157131

	format = " %volume"
	format_muted = " (%volume)"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}

tztime local {
	# format = "%Y-%m-%d %H:%M:%S"
	format = " %d.%m %H:%M "
}
