# Dotbro's configuration file.
# Note that you can use $ENV_VARIABLE in paths.

[directories]

# Directory where your dotfiles repository is stored.
# Default: directory of this config.
dotfiles = "$DOTFILES_ROOT"

# Destination directory - your dotfiles will be linked there.
destination = "$HOME"

# Backup directory - your original files will be backuped here.
backup = "$HOME/.dotfiles~"

[mapping]

# Binaries
"bin" = "bin"

#
# Shell
#

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

# ZSH
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/os-specific/plugins_macos.sh" = ".zshrc.d/11-plugins_macos.sh"
"zsh/os-specific/aliases_macos.sh" = ".zshrc.d/21-aliases_macos.sh"
"zsh/os-specific/keybindings_macos.sh" = ".zshrc.d/31-keybindings_macos.sh"

#
# Editors
#

# Atom
"atom/config.cson" = ".atom/config.cson"
"atom/init.coffee" = ".atom/init.coffee"
"atom/keymap.cson" = ".atom/keymap.cson"
"atom/snippets.cson" = ".atom/snippets.cson"
"atom/styles.less" = ".atom/styles.less"
"atom/packages.list#macos" = ".atom/packages.list"

# Vim
"vim/vimrc" = ".vimrc"

#
# Other
#

"git/gitconfig_macos" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"git/gitexcludes" = ".gitexcludes"
"surfingkeys.js" = ".surfingkeys.js"
