# Dotbro's configuration file.
# Note that you can use $ENV_VARIABLE in paths.

[directories]

# Directory where your dotfiles repository is stored.
# Default: directory of this config.
dotfiles = "$DOTFILES_ROOT"

# Destination directory - your dotfiles will be linked there.
destination = "$HOME"

# Backup directory - your original files will be backuped here.
backup = "$HOME/.dotfiles~"

[mapping]

# Binaries
"bin" = "bin"

#
# Shell
#

"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

# Libraries
"shell/libraries" = ".sh"

# BASH
"bash/bashrc.d" = ".bashrc.d"
"bash/bashrc" = ".bashrc"
"bash/bash_logout" = ".bash_logout"
"bash/bash_profile" = ".bash_profile"
".inputrc" = ".inputrc"

# ZSH
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"

#
# Editors
#

# PhpStorm 10
"WebIde100/config/colors" = ".WebIde100/config/colors"
"WebIde100/config/codestyles" = ".WebIde100/config/codestyles"
"WebIde100/config/keymaps" = ".WebIde100/config/keymaps"
"WebIde100/config/options" = ".WebIde100/config/options"
"WebIde100/config/templates" = ".WebIde100/config/templates"
"WebIde100/phpstorm64.vmoptions" = ".WebIde100/phpstorm64.vmoptions"
"PhpStorm2016/config/colors" = ".PhpStorm2016.1/config/colors"
"PhpStorm2016/config/codestyles" = ".PhpStorm2016.1/config/codestyles"
"PhpStorm2016/config/keymaps" = ".PhpStorm2016.1/config/keymaps"
"PhpStorm2016/config/options" = ".PhpStorm2016.1/config/options"
"PhpStorm2016/config/templates" = ".PhpStorm2016.1/config/templates"
"PhpStorm2016/phpstorm64.vmoptions" = ".PhpStorm2016.1/phpstorm64.vmoptions"

# Atom
"atom/config.cson" = ".atom/config.cson"
"atom/init.coffee" = ".atom/init.coffee"
"atom/keymap.cson" = ".atom/keymap.cson"
"atom/snippets.cson" = ".atom/snippets.cson"
"atom/styles.less" = ".atom/styles.less"
"atom/packages.list" = ".atom/packages.list"

# Vim
"vim/vimrc" = ".vimrc"

#
# Other
#

".xinitrc" = ".xinitrc"
".xprofile" = ".xprofile"
".Xresources" = ".Xresources"
"Xresources.d" = ".Xresources.d"

"git/gitcommit" = ".gitcommit"
"git/gitconfig" = ".gitconfig"
"git/gitexcludes" = ".gitexcludes"

".keynavrc" = ".keynavrc"
".mongorc.js" = ".mongorc.js"
".screenrc" = ".screenrc"

"i3" = ".i3"
"conky" = ".config/conky"
"i3-scrot.conf" = ".config/i3-scrot.conf"

".ctags" = ".ctags"
