# Dotbro's configuration file.
# Note that you can use $ENV_VARIABLE in paths.

[directories]

# Directory where your dotfiles repository is stored.
# Default: directory of this config.
dotfiles = "$DOTFILES_ROOT"

# Destination directory - your dotfiles will be linked there.
destination = "$HOME"

# Backup directory - your original files will be backuped here.
backup = "$HOME/.dotfiles~"

[mapping]

# Binaries
"bin" = "bin"

#
# Shell
#

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

# ZSH
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/plugins/list.sh#macos" = ".zshrc.d/plugins/list.sh"
"zsh/aliases/list.sh#macos" = ".zshrc.d/aliases/list.sh"

#
# Editors
#

# Gogland
"Gogland/config/options/editor.codeinsight.xml" = "Library/Preferences/Gogland1.0/options/editor.codeinsight.xml"
"Gogland/config/templates" = "Library/Preferences/Gogland1.0/templates"

# Atom
"atom/config.cson" = ".atom/config.cson"
"atom/init.coffee" = ".atom/init.coffee"
"atom/keymap.cson" = ".atom/keymap.cson"
"atom/snippets.cson" = ".atom/snippets.cson"
"atom/styles.less" = ".atom/styles.less"
"atom/packages.list#macos" = ".atom/packages.list"

#
# Other
#

"git/gitcommit" = ".gitcommit"
"git/gitconfig" = ".gitconfig"
"git/gitexcludes" = ".gitexcludes"
