# Dotbro's configuration file.
# Note that you can use $ENV_VARIABLE in paths.

[directories]

# Directory where your dotfiles repository is stored.
# Default: directory of this config.
dotfiles = "$DOTFILES_ROOT"

# Destination directory - your dotfiles will be linked there.
destination = "$HOME"

# Backup directory - your original files will be backuped here.
backup = "$HOME/.dotfiles~"

[mapping]

# Binaries
"bin" = "bin"

#
# Shell
#

"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

# Libraries
"shell/libraries" = ".sh"

# BASH
"bash/bashrc.d" = ".bashrc.d"
"bash/bashrc" = ".bashrc"
"bash/bash_logout" = ".bash_logout"
"bash/bash_profile" = ".bash_profile"
".inputrc" = ".inputrc"

# ZSH
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/plugins/list.sh#linux" = ".zshrc.d/plugins/list.sh"

#
# Editors
#

# PhpStorm
"PhpStorm2017/config/colors" = ".PhpStorm2017.1/config/colors"
"PhpStorm2017/config/codestyles" = ".PhpStorm2017.1/config/codestyles"
"PhpStorm2017/config/keymaps" = ".PhpStorm2017.1/config/keymaps"
"PhpStorm2017/config/options/code.style.schemes.xml" = ".PhpStorm2017.1/config/options/code.style.schemes.xml"
"PhpStorm2017/config/options/colors.scheme.xml" = ".PhpStorm2017.1/config/options/colors.scheme.xml"
"PhpStorm2017/config/options/editor.xml" = ".PhpStorm2017.1/config/options/editor.xml"
"PhpStorm2017/config/options/keymap.xml" = ".PhpStorm2017.1/config/options/keymap.xml"

"PhpStorm2017/config/templates/JavaScript.xml" = ".PhpStorm2017.1/config/templates/JavaScript.xml"
"PhpStorm2017/config/templates/Markdown.xml" = ".PhpStorm2017.1/config/templates/Markdown.xml"
"PhpStorm2017/config/templates/PHP.xml" = ".PhpStorm2017.1/config/templates/PHP.xml"

"PhpStorm2017/phpstorm64.vmoptions" = ".PhpStorm2017.1/phpstorm64.vmoptions"
"PhpStorm2017/idea.properties" = ".PhpStorm2017.1/idea.properties"
"PhpStorm2017/watchers.xml" = ".PhpStorm2017.1/watchers.xml"

# Gogland
"Gogland/config/colors" = ".Gogland1.0/config/colors"
"Gogland/config/keymaps/Hypnoglow.xml#linux" = ".Gogland1.0/config/keymaps/Hypnoglow.xml"
"Gogland/config/options/colors.scheme.xml" = ".Gogland1.0/config/options/colors.scheme.xml"
"Gogland/config/options/editor.codeinsight.xml" = ".Gogland1.0/config/options/editor.codeinsight.xml"
"Gogland/config/options/keymap.xml" = ".Gogland1.0/config/options/keymap.xml"
"Gogland/config/templates" = ".Gogland1.0/config/templates"
"Gogland/gogland64.vmoptions" = ".Gogland1.0/gogland64.vmoptions"
"Gogland/idea.properties" = ".Gogland1.0/idea.properties"

# Atom
"atom/config.cson" = ".atom/config.cson"
"atom/init.coffee" = ".atom/init.coffee"
"atom/keymap.cson" = ".atom/keymap.cson"
"atom/snippets.cson" = ".atom/snippets.cson"
"atom/styles.less" = ".atom/styles.less"
"atom/packages.list#linux" = ".atom/packages.list"

# Vim
"vim/vimrc" = ".vimrc"

#
# Other
#
"autorandr" = ".autorandr"

".xinitrc" = ".xinitrc"
".xprofile" = ".xprofile"
".Xresources" = ".Xresources"
"Xresources.d" = ".Xresources.d"

"git/gitcommit" = ".gitcommit"
"git/gitconfig" = ".gitconfig"
"git/gitexcludes" = ".gitexcludes"

".keynavrc" = ".keynavrc"
".mongorc.js" = ".mongorc.js"
".screenrc" = ".screenrc"
"coffeelint.json" = "coffeelint.json"
"surfingkeys.js" = ".surfingkeys.js"

"i3" = ".i3"
"conky" = ".config/conky"
"i3-scrot.conf" = ".config/i3-scrot.conf"
"rofi" = ".config/rofi"

".ctags" = ".ctags"
