# Dotbro's configuration file.
# Note that you can use $ENV_VARIABLE in paths.

[directories]

# Directory where your dotfiles repository is stored.
# Default: directory of this config.
dotfiles = "$DOTFILES_ROOT"

# Destination directory - your dotfiles will be linked there.
destination = "$HOME"

# Backup directory - your original files will be backuped here.
backup = "$HOME/.dotfiles~"

[mapping]

# Binaries
"bin" = "bin"

#
# Shell
#

"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

# Libraries
"shell/libraries" = ".sh"

# BASH
"bash/bashrc.d" = ".bashrc.d"
"bash/bashrc" = ".bashrc"
"bash/bash_logout" = ".bash_logout"
"bash/bash_profile" = ".bash_profile"
".inputrc" = ".inputrc"

# ZSH
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/os-specific/plugins_linux.sh" = ".zshrc.d/11-plugins_linux.sh"
"zsh/os-specific/aliases_linux.sh" = ".zshrc.d/21-aliases_linux.sh"

#
# Editors
#

# Atom
"atom/config.cson" = ".atom/config.cson"
"atom/init.coffee" = ".atom/init.coffee"
"atom/keymap.cson" = ".atom/keymap.cson"
"atom/snippets.cson" = ".atom/snippets.cson"
"atom/styles.less" = ".atom/styles.less"
"atom/packages.list#linux" = ".atom/packages.list"

# Vim
"vim/vimrc" = ".vimrc"

#
# Other
#
"autorandr" = ".autorandr"

".xinitrc" = ".xinitrc"
".xprofile" = ".xprofile"
".Xresources" = ".Xresources"
"Xresources.d" = ".Xresources.d"

"git/gitconfig_linux" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"git/gitexcludes" = ".gitexcludes"

".keynavrc" = ".keynavrc"
".mongorc.js" = ".mongorc.js"
".screenrc" = ".screenrc"
"coffeelint.json" = "coffeelint.json"
"surfingkeys.js" = ".surfingkeys.js"

"i3" = ".i3"
"conky" = ".config/conky"
"i3-scrot.conf" = ".config/i3-scrot.conf"
"rofi" = ".config/rofi"

".ctags" = ".ctags"
