#!/bin/bash
# This script installs all dotfiles by symlinking them to $HOME directory.
################################################################################

# define params
DO_UPDATE=true
VERBOSE=""
DRY_RUN=false

# process params
for param in "$@"
do
case $param in
    -n|--update=no*)
        DO_UPDATE=false
    ;;
    -v|--verbose)
        VERBOSE="-v"
    ;;
    -d|--dry-run)
        DRY_RUN=true
    ;;
    *)
    ;;
esac
done

# self-update if need
if [ $DO_UPDATE = true ] ; then
    if ! type -P git > /dev/null ; then
        echo "Git is not installed - not doing an update"
    elif [ `git rev-parse --abbrev-ref HEAD` = "master" ] ; then
        echo -n "Self updating... "
        git pull --quiet --recurse-submodules
        git submodule update --quiet --init --recursive
        echo "done."
    fi
fi

# Determine path variables
DOTFILES_ROOT=`dirname $( readlink -f ${BASH_SOURCE[0]} )`
DOTFILES_DIR="${DOTFILES_ROOT}/src"
BACKUP_DIR="~/.dotfiles~"

# Define variables needed for further processing
MAPPING_DELIMETER="->"

# All source files in ${DOTFILES_DIR} directory
# should be symlinked to $HOME relatively,
# according to the rules defined in mapper file.
echo "Installing directories"
while read line || [[ -n "$line" ]]; do
    # skip comments - lines starting with #
    [ "${line:0:1}" = "#" ] && continue

    # skip empty lines
    [ "${line}" = "" ] && continue

    SRC=`echo ${line%${MAPPING_DELIMETER}*}`
    DEST=`echo ${line#*${MAPPING_DELIMETER}}`

    # Check if source file exists
    if [ ! -e "$DOTFILES_DIR/$SRC" ] ; then
        echo >&2 "Error: source file from mapping $DOTFILES_DIR/$SRC does not exist."
        continue
    fi

    # if destination file is a symlink - delete it; elseif exists - backup
    if [ -L "$HOME/$DEST" ] ; then
        if [ ${DRY_RUN} = true ] ; then
            echo "Removing $HOME/$DEST"
        else
            rm ${VERBOSE} "$HOME/$DEST"
        fi
    elif [ -e "$HOME/$DEST" ] ; then
        if [ ${DRY_RUN} = true ] ; then
            echo "Moving $HOME/$DEST to $BACKUP_DIR/$DEST"
        else
            mkdir -p ${VERBOSE} `dirname "$BACKUP_DIR/$DEST"`
            mv -f ${VERBOSE} "$HOME/$DEST" "$BACKUP_DIR/$DEST"
        fi
    fi

    if [ ${DRY_RUN} = true ] ; then
        echo "Symlinking $HOME/$DEST -> $DOTFILES_DIR/$SRC"
    else
        ln -sfn ${VERBOSE} "$DOTFILES_DIR/$SRC" "$HOME/$DEST"
    fi
done < "$DOTFILES_ROOT/mapping"

echo "Installation finished."
exit 0
