# Dotbro's configuration file.
# See: https://github.com/hypnoglow/dotbro#configuration
# Note that you can use $ENV_VARIABLE in paths.

[directories]

dotfiles = "$HOME/sources/github.com/hypnoglow/dotfiles"
destination = "$HOME"
backup = "$HOME/.dotfiles~"

[mapping]

"bin" = "bin"

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

"zsh/lib" = ".zsh/lib"
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshenv" = ".zshenv"
"zsh/zshrc.d" = ".zshrc.d"

"git/gitconfig_linux" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"git/gitexcludes" = ".gitexcludes"

"kitty/kitty.conf" = ".config/kitty/kitty.conf"

"i3-reforged/config" = ".config/i3/config"
"i3-reforged/i3blocks-config" = ".config/i3blocks/config"

"compton.conf" = ".compton.conf"
"fontconfig/fonts.conf" = ".config/fontconfig/fonts.conf"
"starship.toml" = ".config/starship.toml"

"neovim/init.vim" = ".config/nvim/init.vim"
"neovim/ftplugin/sh.vim" = ".config/nvim/ftplugin/sh.vim"
"neovim/ftplugin/yaml.vim" = ".config/nvim/ftplugin/yaml.vim"

"vscode/settings.json" = ".config/Code - OSS/User/settings.json"
"vscode/keybindings-linux.json" = ".config/Code - OSS/User/keybindings.json"

"profiles/mizar/xinitrc" = ".xinitrc"
