# Dotbro's configuration file.
# See: https://github.com/hypnoglow/dotbro#configuration
# Note that you can use $ENV_VARIABLE in paths.

[directories]

dotfiles = "$HOME/sources/github.com/hypnoglow/dotfiles"
destination = "$HOME"
backup = "$HOME/.dotfiles~"

[mapping]

"bin" = "bin"

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshrc.d" = ".zshrc.d"
"zsh/os-specific/plugins_macos.sh" = ".zshrc.d/11-plugins_macos.sh"
"zsh/os-specific/aliases_macos.sh" = ".zshrc.d/21-aliases_macos.sh"
"zsh/os-specific/keybindings_macos.sh" = ".zshrc.d/31-keybindings_macos.sh"

"vscode/keybindings.json" = "Library/Application Support/Code/User/keybindings.json"
"vscode/settings.json" = "Library/Application Support/Code/User/settings.json"

"vim/vimrc" = ".vimrc"

"neovim/init.vim" = ".config/nvim/init.vim"
"neovim/ftplugin/yaml.vim" = ".config/nvim/ftplugin/yaml.vim"

"git/gitconfig_macos" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"git/gitexcludes" = ".gitexcludes"
"git/hooks" = ".githooks"

"macOS/karabiner" = ".config/karabiner"
