#
# User configuration sourced by interactive shells
#

# Emacs mode
bindkey -e

PURE_PROMPT_SYMBOL="ή"

# Source zim framework
[[ -d ~/.zim ]] || {
    git clone --recursive https://github.com/Eriner/zim.git ${ZDOTDIR:-${HOME}}/.zim
}
source ${ZDOTDIR:-${HOME}}/.zim/init.zsh

#
# Rewrite zim settings below
#

# MORE history
HISTFILE=~/.zhistory
HISTSIZE=100000
SAVEHIST=100000

#
# Plugins
#

[[ -d ~/.zplug ]] || {
    git clone https://github.com/zplug/zplug ${ZPLUG_HOME:-"${HOME}/.zplug"}
}

source ~/.zplug/init.zsh

zplug "seletskiy/zsh-ssh-urxvt"
if [ "$TERM" != "linux" ]; then
    zplug "zsh-users/zsh-autosuggestions"
fi

if ! zplug check --verbose; then
  printf "Install zsh plugins? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

#
# Custom
#

# Include all from ~/.zshrc.d
if [ -d ${HOME}/.zshrc.d ]; then
    for file in ${HOME}/.zshrc.d/*.sh ; do
        [ -r ${file} ] && . ${file}
    done
    unset file
fi
