#
# User configuration sourced by interactive shells
#

# Emacs mode
bindkey -e

# Source zim framework
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

#
# Rewrite zim settings below
#

# MORE history
HISTFILE=~/.zhistory
HISTSIZE=100000
SAVEHIST=100000

#
# Custom
#

# Include all from ~/.bashrc.d
if [ -d ${HOME}/.zshrc.d ]; then
    for file in ${HOME}/.zshrc.d/*.sh ; do
        [ -r ${file} ] && . ${file}
    done
    unset file
fi
