#
# User configuration sourced by all invocations of the shell
#

# Define Zim location
: ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}

# https://github.blog/changelog/2026-04-22-github-cli-opt-out-usage-telemetry/
export GH_TELEMETRY=false
export DO_NOT_TRACK=true
