# ~/.zshenv is sourced universally for all types of shell sessions (interactive or non-interactive, login or non-login).
# It is the only configuration file that gets loaded for non-interactive and non-login scripts like cron jobs.
# However, macOS overrides this for PATH settings for interactive shells.

# Define Zim location
: ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}

# https://github.blog/changelog/2026-04-22-github-cli-opt-out-usage-telemetry/
export GH_TELEMETRY=false
export DO_NOT_TRACK=true
