# ~/.bashrc: executed by bash(1) for interactive non-login shells.

# However, in ~/.profile , there is a ~/.bashrc include, 
# so, actually, it IS executed for login shells also.

################################################################################

# If not running interactively, don't do anything.
#!# $- = Flags passed to script (using set).
# ref: http://tldp.org/LDP/abs/html/internalvariables.html
if [[ $- != *i* ]] ; then
	return
fi

# Load all files from .bashrc.d directory
#if [ -d $HOME/.bashrc.d ] ; then
#	for file in $HOME/.bashrc.d/*.bash ; do
#		source $file
#	done
#fi

# Prevents from redirecting output to an existing file, or appending output to a non-existing file.
# ref: http://www.xinotes.net/notes/note/57/
# ref: https://books.google.ru/books?id=N--YV7uyDI8C&pg=PA413&lpg=PA413&dq=set+-o+noclobber&source=bl&ots=wkbJapeGhc&sig=8SMFvbY59UnblmmissX_OBvLX3M&hl=ru&sa=X&ved=0CEQQ6AEwBWoVChMIg6PR6rGFxwIVC10UCh1RqASr#v=onepage&q=set%20-o%20noclobber&f=false
# (To unset it clearly: "set +o noclobber", which is default)
set -o noclobber

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

################################################################################

# All STDERR output is in red color.
# https://github.com/sickill/stderred
if [ -f /home/zibarev/utils/stderred/build/libstderred.so ]
then
    export LD_PRELOAD="/home/zibarev/utils/stderred/build/libstderred.so${LD_PRELOAD:+:$LD_PRELOAD}"
fi

# Bash-it
if [ -f ~/.bash_bashit ]; then
    . ~/.bash_bashit
fi

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

################################################################################

