# ~/.bash_profile: executed by bash(1) for login shells.
#
# Bash runs FIRST of:
# ~/.bash_profile
# ~/.bash_login
# ~/.profile
# Others will not run!

. "$HOME/.profile"

# Login shell does not include .bashrc,
# so manually include it
if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
fi
